<template>
    <div class="">
        
   
        <table class="table is-striped is-hoverable is-fullwidth">
    <thead class="has-background-black-bis ">
      <tr>
        <th class="has-text-grey">Block Height</th>
        <th class="has-text-grey">Age</th>
        <th class="has-text-grey">Generated By</th>
        <th class="has-text-grey">Transactions</th>
        <th class="has-text-grey">Total Reward (NOSO)</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th class="has-text-grey-light">156766</th>
        <td>10 min ago</td>
        <td>NpryectdevepmentfundsGE</td>
        <td>0</td>
        <td>50</td>
      </tr>
      <tr>
        <th>156766</th>
        <td>10 min ago</td>
        <td>NpryectdevepmentfundsGE</td>
        <td>0</td>
        <td>50</td>
      </tr>
      <tr>
        <th>156766</th>
        <td>10 min ago</td>
        <td>NpryectdevepmentfundsGE</td>
        <td>0</td>
        <td>50</td>
      </tr>
      <tr>
        <th>156766</th>
        <td>10 min ago</td>
        <td>NpryectdevepmentfundsGE</td>
        <td>0</td>
        <td>50</td>
      </tr>
   
    </tbody>
  </table>
    </div>
  </template>
  
  <script>
  export default {
    name: 'BlocksFragment' 
  }
  </script>
  